### ISSUE TITLE
Cannot build and run the simple demo code

### ISSUE THREAD

**Issue by AllenDang** [darthdeus/comfy#11]
Here is the repo steps:
1. `cargo new --bin comfy_test`
2. `cd comfy_test`
3. `cargo add comfy`
4. Enter following code to main.rs
```rust
use comfy::*;

simple_game!("Nice red circle", update);

fn update(_c: &mut EngineContext) {
    draw_circle(vec2(0.0, 0.0), 0.5, RED, 0);
}
```
5. `cargo run`

Error message is
```
:!cargo run
   Compiling comfy_test v0.1.0 (/Users/allen/Documents/RustProjects/comfy_test)
error: proc macro panicked
 --> src/main.rs:3:1
  |
3 | simple_game!("Nice red circle", update);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "git describe failed with status 128: fatal: Not a valid object name HEAD" }
  = note: this error originates in the macro `define_versions` which comes from the expansion of the macro `simple_game` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `comfy_test` (bin "comfy_test") due to 2 previous errors

shell returned 101
```

**Comment by darthdeus** [comment]
Hi, sorry for this issue! The issue here is comfy ends up calling `git describe` to embed git version into the game, but this will fail if you created a new repo and don't have a single commit.

The way comfy calls git is not robust enough, so it ends up crashing. I'll fix this later today, but for now you can just make a `git commit -m "initial commit"` and it should work.

Note that there was also another bug in the version on crates.io which I just fixed and published `v0.1.1`, so please make sure to change your `Cargo.toml` to use the newer version, otherwise you might get a different crash :)

Sorry for the mess! It's the first time I'm publishing a multi-workspace crate and there were quite a few problems with bugs I had to fix on last minute yesterday to make `cargo publish` work, so there were a few bugs introduced as a side effect.

But I just tested again on a new empty crate, made a commit, added comfy, copy pasted in the example and it compiled, so it should be good now :)

**Comment by AllenDang** [comment]
Still experience error on `cargo run`, here is the error log
```
   Compiling kira v0.8.5
   Compiling comfy-core v0.1.1
   Compiling comfy-wgpu v0.1.1
   Compiling comfy v0.1.1
   Compiling comfy_test v0.1.0 (/Users/allen/Documents/RustProjects/comfy_test)
    Finished dev [unoptimized + debuginfo] target(s) in 17.14s
     Running `target/debug/comfy_test`
LOGGER: env_logger
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Requested usage is not supported
', /Users/allen/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.16.3/src/backend/direct.rs:734:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

shell returned 101
```

**Comment by darthdeus** [comment]
That's strange, looks like your GPU doesn't support what wgpu is asking for. What CPU/GPU/OS are you on?

**Comment by AllenDang** [comment]
I'm using macOS v13 with M1 (amd64)

**Comment by darthdeus** [comment]
Thanks! Looks like this is indeed Mac specific, I was able to reproduce it on my Macbook. I'll hopefully have a fix for it later today, it's something with how comfy configures the wpgu surface. It doesn't look like it'll be too difficult (for sure worked a few weeks ago :) ), but I have to do other things now so I won't be able to look deeply into it until later today.

**Comment by darthdeus** [comment]
I published a new version `0.1.2` that should fix this issue, at least it does on my Mac. Feel free to reopen if it still crashes :)
